### ISSUE TITLE
Option to change string of total score modifier in difficulty menu

### ISSUE THREAD

**Issue by LadyAlekto** [BattletechModders/IRTweaks#12]
Id like to change it to something else like "overall difficulty value" since "score" doesnt matter for rt

![20200106223123_1](https://user-images.githubusercontent.com/39632036/71850475-a81e9d00-30d4-11ea-8bb2-cd5c42e239c8.jpg)

**Comment by IceRaptor** [comment]
Provided in 0.6.6.
