### ISSUE TITLE
Feature request: %chance to proc additional stab damage

### ISSUE THREAD

**Issue by IceRaptor** [BattletechModders/IRTweaks#60]
Per discussion with BD - it could be interesting for GUN increases to proc an additional % of stability damage from the attack. Something like 'Gun 5 gives a 25% chance to proc an additional %50 damage on hit'. 

tbone notes there's a CAC/AIM API for changing damage which could be easily used for this effect.

**Comment by ajkroeg** [comment]
Implemented
