### ISSUE TITLE
Feature request: Gun + pilot ability procs status effect on hit

### ISSUE THREAD

**Issue by IceRaptor** [BattletechModders/IRTweaks#61]
Per discussion with BTA, a tweak that allows application of a status effect to a target unit on hit would be interested. Gated / specified by Gun level perhaps.

--- BEGIN ---
At certain tiers of Gun, when hitting arms/legs/head proc a status effect with a duration driven by Gun value would be pretty easy
Could this be done such that it is not enabled automatically by taking gunnery but is activated by taking a pilot ability? So that we could make a, say, Gunnery 10 pilot skill that activates this functionality?
Because I really like the idea of weapons fire causing debuffs but don't like the idea of it being on every pilot all the time.
That's something I'd want in a specific pilot skill so that it is a choice to be activated.
FrostRaptor — Today at 12:46 PM
From a vanilla standpoint - yes, I do that all the time in my mods. I check the skill + modify it if the pilot has a specific ability.

How that works with all the new ability stuff t-bone and Jamie added I can't speak to.
bloodydoves — Today at 12:47 PM
basically, could it be added to IRTweaks or whatever with a statname that "activates" it
and that without that statname it doesn't take effect
that's all I'd need
just a way to flag it on and off
FrostRaptor — Today at 12:47 PM
For example, here's how I calculate Tactics Mods for SBI, LowVis:
        public static int GetTacticsModifier(Pilot pilot) {
            return GetModifier(pilot, pilot.Tactics, "AbilityDefT5A", "AbilityDefT8A");
        }
Oh yeah, statname? No problem.
bloodydoves — Today at 12:47 PM
so that I could make a pilot skill that turns it on for that pilot via statname
I'd also want configuration so I could set the various debuffs etc
legs/arms/torsos/head would probably be necessary locations
FrostRaptor — Today at 12:49 PM
Yeah, I think we'd be talking about a simple patch on AttackDirector.OnAttackSequenceEnd to check for a hit, if hit check attacker for enablement, then apply status effect to target
Famous last words but I think that'd be fairly straightforward.

**Comment by ajkroeg** [comment]
Implemented
